### ISSUE TITLE
Typo on ...options.

### ISSUE THREAD

**Issue by bakitoktas** [sindresorhus/del#104]
https://github.com/sindresorhus/del/blob/c07118089d4e6a4f7df689be888b90b989183d0c/index.js#L22

**Comment by sindresorhus** [comment]
What is the typo?

**Comment by bakitoktas** [comment]
..options is throwing this error:

`node_modules/del/index.js:22
module.exports = async (patterns, {force, dryRun, ...options} = {}) => {
                                                  ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bakitoktas/Sites/mailshop.co.uk/mailshop/magento/skin/frontend/platform/gulpfile.js:6:19)
    at Module._compile (module.js:570:32)`

**Comment by chrisblossom** [comment]
I'm guessing you are using an unsupported version of node. You need node v8.9 or greater.
