### ISSUE TITLE
I can't deploy turbo successfully 

### ISSUE THREAD

**Issue by Blacjar** [sindresorhus/del#121]
I have everything working well untill now. 
I typed- npm run build- success
I type - turbo deploy ( I get errors I=even when I try from a different network provider its another error .

this is my result 

Deploying to Turbo 360 Hosting Environment...

added 213 packages from 156 contributors and audited 695 packages in 4.376s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

.......events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 52.216.26.4:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
Emitted 'error' event on Stream instance at:
    at Stream.onerror (/usr/local/lib/node_modules/turbo-cli/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Stream.emit (events.js:223:5)
    at Stream.EventEmitter.emit (domain.js:475:20)
    at next (/usr/local/lib/node_modules/turbo-cli/node_modules/map-stream/index.js:74:19)
    at /usr/local/lib/node_modules/turbo-cli/node_modules/map-stream/index.js:84:7
    at /usr/local/lib/node_modules/turbo-cli/dist/aws/index.js:1:4204
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/turbo-cli/dist/aws/index.js:1:1956)
    at ClientRequest.f (/usr/local/lib/node_modules/turbo-cli/node_modules/once/once.js:25:25)
    at ClientRequest.emit (events.js:223:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '52.216.26.4',
  port: 443
}

pls I need help, I'm frustrated..

**Comment by sindresorhus** [comment]
This has nothing to do with `del`.
