### ISSUE TITLE
=> this operator and how to use it?

### ISSUE THREAD

**Issue by meffect** [sindresorhus/del#31]
How do you use this "=>". My gulp doesn't like it. I'm familiar with it in a C# context , where it means 'goes to'. Seems the same here.. but gulp doesn't understand it?

```
gulp.task('clean', function (cb) {
    del(['./dist/*']).then(paths => {      
    });
});

$ gulp
gulpfile.js:23
    del(['./dist/*']).then(paths => {
                                 ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (C:\Program Files\nodejs\node_modules\gulp\bin\gulp.js:116:3)

    at Liftoff.<anonymous> (C:\Program   Files\nodejs\node_modules\gulp\node_modules\liftoff\index.js:192:16) 
at module.exports (C:\Program Files\nodejs\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
```
```
$ gulp -v
[11:02:35] CLI version 3.9.0
[11:02:35] Local version 3.9.0
```

**Comment by sindresorhus** [comment]
It's a arrow function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

Just use a normal function if you don't use Babel for ES2015 support.

**Comment by meffect** [comment]
Makes sense, thanks
