### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by nddery** [sindresorhus/del#41]
Can't figure out what I'm missing.. Trying to adapt some version 1 code to version 2.

I have a file with the following content:

```js
var del = require('del')

del(['.tmp', 'dist']).then(function(paths) {
  console.log(paths);
});
```

which I run on the command line like so:

```bash
$ node my_file.js
```

This results in the following error:

```js
TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (/path/to/file:3:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

I'm running Node `v4.1.2` on Mac OSX 10.11.

**Comment by schnittstabil** [comment]
`del` returns `undefined` in version 1.x. Maybe you messed up your `node_modules` directory, and/or a version 1.x is globally installed.

**Comment by nddery** [comment]
Deleted `node_modules` and re-installed.. Now working.. Not sure what happened. Thanks thought!
