### ISSUE TITLE
Build is failing with error TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by logztechstuff** [sindresorhus/del#58]
[15:14:09] TypeError in plugin 'run-sequence(clean:dist)'
Message:
    Cannot read property 'length' of undefined
Stack:
TypeError: Cannot read property 'length' of undefined
    at Function.glob.hasMagic /node_modules/del/node_modules/rimraf/node_modules/glob/glob.js:106:29)
    at Function.rimrafSync [as sync] (/node_modules/del/node_modules/rimraf/rimraf.js:272:36)
    at /home/loganathan/git/mysite/node_modules/del/index.js:68:11
    at Array.map (native)
    at Function.module.exports.sync (/home/loganathan/git/mysite/node_modules/del/index.js:60:37)
    at Gulp.<anonymous> (/home/loganathan/git/mysite/gulpfile.js:131:14)
    at module.exports /home/loganathan/git/mysite/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/loganathan/git/mysite/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/loganathan/git/mysite/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/loganathan/git/mysite/node_modules/gulp/node_modules/orchestrator/index.js:134:8)

**Comment by schnittstabil** [comment]
@logztechstuff To be able to help, one needs at least the code of your gulp task – It seems, your glob patterns got messed up in some way…

**Comment by hamishtaplin** [comment]
Just started randomly getting this too. All worked fine for months and I haven't changed anything that is related to this. Some dependency has changed maybe?

**Comment by schnittstabil** [comment]
Related: [isaacs/node-glob#283: Cannot read property 'length' of undefined at Function.glob.hasMagic](https://github.com/isaacs/node-glob/issues/283)

**Comment by hamishtaplin** [comment]
Yep, also seeing that error with `glob.hasMagic` elsewhere.

**Comment by schnittstabil** [comment]
@hamishtaplin https://github.com/isaacs/minimatch was updated 14 days ago

**Comment by sindresorhus** [comment]
Probably related to https://github.com/redhivesoftware/math-expression-evaluator/pull/2.
