### ISSUE TITLE
Not able to delete not empty directories windows 10

### ISSUE THREAD

**Issue by maqboolkhan** [sindresorhus/del#59]
i have my folder structures like
```
- scripts
  - components
    - index.js
  - main.js
- styles
  - components
    - button.css
  - main.css
```

now i want to delete above folders so i did

`del.sync(['./build/scripts/', './build/styles/'])`

but it throws

```
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Maqbool\Desktop\Temperature\hrefli\.temp\scripts'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\Maqbool\Desktop\Temperature\hrefli\node_modules\del\node_modules\rimraf\rimraf.js:342:11)
    at rmdirSync (C:\Users\Maqbool\Desktop\Temperature\hrefli\node_modules\del\node_modules\rimraf\rimraf.js:332:7)
    at rimrafSync (C:\Users\Maqbool\Desktop\Temperature\hrefli\node_modules\del\node_modules\rimraf\rimraf.js:303:9)
    at C:\Users\Maqbool\Desktop\Temperature\hrefli\node_modules\del\node_modules\rimraf\rimraf.js:340:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Maqbool\Desktop\Temperature\hrefli\node_modules\del\node_modules\rimraf\rimraf.js:339:26)
    at rmdirSync (C:\Users\Maqbool\Desktop\Temperature\hrefli\node_modules\del\node_modules\rimraf\rimraf.js:332:7)
    at Function.rimrafSync [as sync] (C:\Users\Maqbool\Desktop\Temperature\hrefli\node_modules\del\node_modules\rimraf\rimraf.js:303
:9)
```
 i am on Windows 10 and using `del 2.2.2`

any help welcome thanks

**Comment by SamVerschueren** [comment]
Try using [force](https://github.com/sindresorhus/del#force).

**Comment by sindresorhus** [comment]
Might be related to https://github.com/isaacs/rimraf/commit/d53235de863cfb00f691456288fcf3abbced7f6c. Open an issue on `rimraf`.

**Comment by maqboolkhan** [comment]
thanks @SamVerschueren and @sindresorhus i will check and report and issue there as well 
thanks for your quick reply

**Comment by maqboolkhan** [comment]
@SamVerschueren `force` option worked thanks
